[workspace]
authors = ["Joosep Pata <joosep.pata@gmail.com>"]
channels = ["pytorch", "conda-forge", "bioconda"]
name = "pytorch-train"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"

[tasks]
train = "python train_example.py"
scan = "python scan_params.py"
snakemake = "snakemake"

[dependencies]
python = "*"
libstdcxx-ng = "*"
umap-learn = ">=0.5.11,<0.6"
setuptools = "==81.0.0"

[pypi-dependencies]
colliderml = "*"
numpy = "*"
awkward = "*"
pyarrow = "*"
pandas = "*"
tqdm = "*"
matplotlib = "*"
seaborn = "*"
snakemake = "*"
torch = "*"
torchvision = "*"
torchaudio = "*"
tensorboard = ">=2.20.0"
setuptools = "==81.0.0"
